language: cpp
compiler:
  - gcc
before_install:
 - yes | sudo add-apt-repository ppa:canonical-qt5-edgers/qt5-proper
 - yes | sudo add-apt-repository ppa:gstreamer-developers/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq debhelper qtbase5-dev qt5-default libqt5webkit5-dev cdbs devscripts qtlocation5-dev qtsensors5-dev qtquick1-5-dev qtdeclarative5-dev libxslt1-dev libgstreamer0.10-dev libsqlite3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-base0.10-dev libqt5opengl5-dev
 - cd src
 - git clone git://github.com/vranki/libsiilihai.git
 - cd ..
 - qmake CONFIG+=with_lib
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - ville.ranki@iki.fi
  email:
    on_success: change
    on_failure: always

